services:
  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservice-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 25s # Memberikan waktu 25 detik pertama bagi JVM/Spring untuk menyala sebelum mulai dihitung gagal
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - microservice-net
    depends_on:
      - eureka-server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - microservice-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  produk:
    build: ./produk
    container_name: produk
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      # Perbaikan Path Database agar sesuai dengan volume /data
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/produk;DB_CLOSE_ON_EXIT=false;AUTO_RECONNECT=TRUE
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      # Perbaikan penulisan double underscore untuk konvensi Spring Boot dari YAML ke Environment
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    volumes:
      - produk_data:/data
    depends_on:
      - eureka-server  # Memastikan produk baru jalan SETELAH eureka benar-benar siap menerima registrasi
    networks:
      - microservice-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  produk_data:

networks:
  microservice-net:
    driver: bridge