server.port = 8084
spring.application.name=consumer

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=farhanhanifazhary@gmail.com
spring.mail.password=exyuksoskphoddol

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.enabled=true
management.health.show-details=always
management.metrics.export.prometheus.enabled=true